# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'iOS-Tutorials' do
pod 'Material', '~> 1.0'
 pod 'Alamofire', '~> 3.0'
 pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
 pod 'DGElasticPullToRefresh'
 pod 'DLRadioButton', '~> 1.4'
# pod 'ISRadioButton'
 pod 'Kanna', '~> 1.0.0'
end

